#!/bin/sh

for f in /usr/aarch64-linux-*/lib/libc.so /usr/arm-linux-*/lib/libc.so /usr/armv7l-linux-*/lib/libc.so; do
    if [ -f "$f" ]; then
        echo "Updating $f."
        sed -i "$f" -e "s://*lib/l:l:g"
    fi
done
