#!/bin/bash

. arch-arm-cross-config.sh
export ARCH_ARM_CROSS_SYSROOT="${ARCH_ARM_CROSS_PKG_ROOT}/armv7/"

# export PACMAN=pacman-arm-cross

exec makepkg --config "${DATA_DIR}/makepkg-armv7.conf" "$@"
