#!/bin/bash

. arch-arm-cross-config.sh

mkdir -p "${ARCH_ARM_CROSS_SYSROOT}"/var/lib/pacman/

"${EXEC_DIR}/prepare-chroot" "${ARCH_ARM_CROSS_SYSROOT}"
exec pacman --config "${DATA_DIR}/pacman-arm.conf" "$@"
