#!/bin/bash

. arch-arm-cross-config.sh

dbpath_set=0
cachedir_set=0
logfile_set=0
gpgdir_set=0
config_set=0

for ((i = 1;i <= $#;i++)); do
    arg=${!i}
    case "${arg}" in
        --config)
            ((i++))
            config_set=1
            ;;
        -r|--root)
            ((i++))
            export ARCH_ARM_CROSS_SYSROOT="${!i}"
            ;;
        -b|--dbpath)
            ((i++))
            dbpath_set=1
            DBPATH=${!i}
            ;;
        --cachedir)
            ((i++))
            cachedir_set=1
            ;;
        --logfile)
            ((i++))
            logfile_set=1
            ;;
        --gpgdir)
            ((i++))
            gpgdir_set=1
            ;;
    esac
done

((config_set)) || set -- --config "${DATA_DIR}/pacman-arm.conf" "$@"
((dbpath_set)) || {
    DBPATH=${ARCH_ARM_CROSS_SYSROOT}/var/lib/pacman
    set -- --dbpath "${DBPATH}" "$@"
}
((cachedir_set)) ||
    set -- --cachedir "${ARCH_ARM_CROSS_SYSROOT}/var/cache/pacman/pkg/" "$@"
((logfile_set)) ||
    set -- --logfile "${ARCH_ARM_CROSS_SYSROOT}/var/log/pacman.log" "$@"
((gpgdir_set)) ||
    set -- --gpgdir "${ARCH_ARM_CROSS_SYSROOT}/etc/pacman.d/gnupg/" "$@"

echo "ARCH_ARM_CROSS_SYSROOT=${ARCH_ARM_CROSS_SYSROOT}"
echo "$*"

exit

mkdir -p "${DBPATH}"

"${EXEC_DIR}/prepare-chroot" "${ARCH_ARM_CROSS_SYSROOT}"
exec pacman "$@"
